# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('uid', models.CharField(editable=False, max_length=32)),
                ('zhou_min_speed', models.PositiveSmallIntegerField(default=0, verbose_name='\u5468\u6700\u5c11\u82b1\u8d39\u6700\u5c11(*100')),
                ('zhou_min_hours', models.PositiveSmallIntegerField(default=0, verbose_name='\u5468\u65f6\u95f4\u5360\u7528\u5c0f\u65f6')),
                ('fit_age', models.PositiveSmallIntegerField(default=0, verbose_name='\u6700\u65e9\u9002\u5b9c\u5e74\u9f84')),
                ('zonghefenxi', models.PositiveSmallIntegerField(default=0, verbose_name='\u7efc\u5408\u5206\u6790\u80fd\u529b')),
                ('luojituili', models.PositiveSmallIntegerField(default=0, verbose_name='\u903b\u8f91\u63a8\u7406\u80fd\u529b')),
                ('chouxiangsiwei', models.PositiveSmallIntegerField(default=0, verbose_name='\u62bd\u8c61\u601d\u7ef4\u80fd\u529b')),
                ('kongjianxiangxiang', models.PositiveSmallIntegerField(default=0, verbose_name='\u7a7a\u95f4\u60f3\u8c61\u80fd\u529b')),
                ('dulisikao', models.PositiveSmallIntegerField(default=0, verbose_name='\u72ec\u7acb\u601d\u8003\u80fd\u529b')),
                ('dajv_zhengti', models.PositiveSmallIntegerField(default=0, verbose_name='\u5927\u5c40\u89c2/\u6574\u4f53\u89c2')),
                ('zhuanzhu', models.PositiveSmallIntegerField(default=0, verbose_name='\u4e13\u6ce8\u80fd\u529b')),
                ('jisuan', models.PositiveSmallIntegerField(default=0, verbose_name='\u8ba1\u7b97\u80fd\u529b')),
                ('xizhiguancha', models.PositiveSmallIntegerField(default=0, verbose_name='\u7ec6\u81f4\u89c2\u5bdf\u80fd\u529b')),
                ('xiangxiang', models.PositiveSmallIntegerField(default=0, verbose_name='\u60f3\u8c61\u80fd\u529b')),
                ('jiyi', models.PositiveSmallIntegerField(default=0, verbose_name='\u8bb0\u5fc6\u80fd\u529b')),
                ('shenmei', models.PositiveSmallIntegerField(default=0, verbose_name='\u5ba1\u7f8e\u80fd\u529b')),
                ('shouyanxietiao', models.PositiveSmallIntegerField(default=0, verbose_name='\u624b\u773c\u534f\u8c03\u80fd\u529b')),
                ('secaidapei', models.PositiveSmallIntegerField(default=0, verbose_name='\u8272\u5f69\u642d\u914d\u80fd\u529b')),
                ('biaoyan', models.PositiveSmallIntegerField(default=0, verbose_name='\u8868\u6f14\u80fd\u529b')),
                ('jiejuewenti', models.PositiveSmallIntegerField(default=0, verbose_name='\u89e3\u51b3\u95ee\u9898\u80fd\u529b')),
                ('xingtikongzhi', models.PositiveSmallIntegerField(default=0, verbose_name='\u5f62\u4f53\u63a7\u5236\u80fd\u529b')),
                ('shentirouren', models.PositiveSmallIntegerField(default=0, verbose_name='\u8eab\u4f53\u67d4\u97e7\u80fd\u529b')),
                ('zhitixietiao', models.PositiveSmallIntegerField(default=0, verbose_name='\u80a2\u4f53\u534f\u8c03\u80fd\u529b')),
                ('chuangxin', models.PositiveSmallIntegerField(default=0, verbose_name='\u521b\u65b0\u80fd\u529b')),
                ('yuedu', models.PositiveSmallIntegerField(default=0, verbose_name='\u9605\u8bfb\u80fd\u529b')),
                ('shuxie', models.PositiveSmallIntegerField(default=0, verbose_name='\u4e66\u5199\u80fd\u529b')),
                ('yuyanbiaoda', models.PositiveSmallIntegerField(default=0, verbose_name='\u8bed\u8a00\u8868\u8fbe\u80fd\u529b')),
                ('renjijiaowang', models.PositiveSmallIntegerField(default=0, verbose_name='\u4eba\u9645\u4ea4\u5f80\u80fd\u529b')),
                ('tuanduixiezuo', models.PositiveSmallIntegerField(default=0, verbose_name='\u56e2\u961f\u534f\u4f5c\u80fd\u529b')),
                ('zuzhi', models.PositiveSmallIntegerField(default=0, verbose_name='\u7ec4\u7ec7\u80fd\u529b')),
                ('lingdao', models.PositiveSmallIntegerField(default=0, verbose_name='\u9886\u5bfc\u80fd\u529b')),
                ('kangya', models.PositiveSmallIntegerField(default=0, verbose_name='\u6297\u632b\u6298/\u575a\u97e7\u80fd\u529b')),
            ],
            options={
                'verbose_name': '\u6570\u503c\u8868',
                'verbose_name_plural': '\u6570\u503c\u8868',
            },
        ),
        migrations.CreateModel(
            name='AbilityWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('within', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u5185\u5411')),
                ('extrovert', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u5916\u5411')),
                ('no_sure', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u4e0d\u786e\u5b9a')),
                ('boy', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u7537')),
                ('girl', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u5973')),
                ('one', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u4e00\u7c7b')),
                ('two', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u4e8c\u7c7b')),
                ('three', models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='\u4e09\u7c7b')),
            ],
            options={
                'verbose_name': '\u80fd\u529b\u6743\u91cd',
                'verbose_name_plural': '\u80fd\u529b\u6743\u91cd',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('index', models.SmallIntegerField(verbose_name='\u7d22\u5f15')),
                ('name', models.CharField(max_length=50, verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('index', models.SmallIntegerField(verbose_name='\u7d22\u5f15')),
                ('name', models.CharField(max_length=50, verbose_name='\u5174\u8da3')),
            ],
            options={
                'verbose_name': '\u5174\u8da3',
                'verbose_name_plural': '\u5174\u8da3',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('index', models.SmallIntegerField(verbose_name='\u7d22\u5f15')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u80fd\u529b',
                'verbose_name_plural': '\u80fd\u529b',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('order', models.CharField(max_length=32, verbose_name='\u5355\u53f7')),
                ('test_data', models.TextField(max_length=1024, verbose_name='\u6d4b\u8bd5\u6570\u636e')),
                ('test_result', models.TextField(max_length=1024, verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u8bb0\u5f55',
                'verbose_name_plural': '\u6d4b\u8bd5\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='TrainingDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=20, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=20, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('index', models.SmallIntegerField(verbose_name='\u7d22\u5f15')),
                ('name', models.CharField(max_length=50, verbose_name='\u57f9\u517b\u65b9\u5411')),
                ('renzhi', models.IntegerField(verbose_name='\u8ba4\u77e5')),
                ('caozuo', models.IntegerField(verbose_name='\u64cd\u4f5c')),
                ('shejiao', models.IntegerField(verbose_name='\u793e\u4ea4')),
                ('total', models.IntegerField(verbose_name='\u603b\u5206')),
            ],
            options={
                'verbose_name': '\u57f9\u517b\u65b9\u5411',
                'verbose_name_plural': '\u57f9\u517b\u65b9\u5411',
            },
        ),
        migrations.AddField(
            model_name='abilityweight',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.Category', verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='abilityweight',
            name='power_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adapter.Power', verbose_name='\u80fd\u529b'),
        ),
        migrations.AddField(
            model_name='ability',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adapter.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='ability',
            name='hobby_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adapter.Hobbies', verbose_name='\u5174\u8da3'),
        ),
    ]
