# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
